name: EventManager

web:

description: 

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://sharedhat.com/mit-license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "source/event-manager.js"

author: holyshared

category: Utilities

tags: [event, event-manager]

current: 1.0

#docs: http://url_to_plugin_docs
